pages_build_output_dir = "."
name = "file-share-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "FILE_BUCKET"
bucket_name = "mydrive"

[[d1_databases]]
binding = "DB"
database_name = "file-share"
database_id = "2ea19df0-8dd3-4f38-9e50-10f17e526287"    # Will be set during deployment
